version: '3'
services:
  back:
    build: ./back
    ports:
     - "4242:4242"
     - "1337:1337"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
  front:
    build: ./front
    ports:
      - "8080:80"
    volumes:
      - ./front/nginx.conf:/etc/nginx/nginx.conf
  mongo:
    image: 'mongo:latest'
    volumes:
      - ./volumes/mongo:/data/db
