const LOGIN_ACTION = "LOGIN_REQUEST";
const REGISTER_ACTION = "REGISTER_REQUEST";
const LOGOUT_ACTION = "LOGOUT_REQUEST";
const START_ERROR_ACTION = "START_ERROR_ACTION";
const END_ERROR_ACTION = "END_ERROR_ACTION";

/**
 * Rooms Actions
 */
const ROOM_CREATION_ACTION = "ROOM_CREATION_REQUEST";
const ROOM_LIST_ACTION = "ROOM_LIST_REQUEST";
const ROOM_REMOVE_ACTION = "ROOM_REMOVE_REQUEST";

/**
 * Messages Actions
 */
const MESSAGE_LIST_ACTION = "MESSAGE_LIST_REQUEST";
const MESSAGE_CREATE_ACTION = "MESSAGE_CREATE_REQUEST";

/**
 * WS
 */
const NEW_ROOM_ACTION = "NEW_ROOM_ACTION";
const WS_CONNECTED_ACTION = "WS_CONNECTED_ACTION";
const WS_ROOM_CONNECTED_ACTION = "WS_ROOM_CONNECTED_ACTION";
const REMOVED_ROOM_ACTION = "REMOVED_ROOM_ACTION";
const NEW_MESSAGE_ACTION = "NEW_MESSAGE_ACTION";

const actions = {
  LOGIN_ACTION,
  REGISTER_ACTION,
  LOGOUT_ACTION,
  ROOM_CREATION_ACTION,
  ROOM_LIST_ACTION,
  ROOM_REMOVE_ACTION,
  MESSAGE_LIST_ACTION,
  MESSAGE_CREATE_ACTION,
  END_ERROR_ACTION,
  START_ERROR_ACTION,
  WS_CONNECTED_ACTION,
  WS_ROOM_CONNECTED_ACTION,
  NEW_ROOM_ACTION,
  REMOVED_ROOM_ACTION,
  NEW_MESSAGE_ACTION
};

export const initialState = {
  generalReducer: {
    requestProcessing: false,
    loggedIn: false,
    jwt: null,
    error: null,
    socket: null,
    roomSocket: null
  },
  roomReducer: [],
  messageReducer: []
};

export default actions;
